upstream laravel {
    server laravel:9000;
}

upstream nuxt {
    server nuxt:3000;
}

upstream realtime {
    server realtime:3001;
}

server {
    listen 80 default_server;
    server_name xcinema.daw.inspedralbes.cat;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    # Temporalmante servimos por puerto 80 para poder generar los certificados
    # Laravel API
    location /api {
        proxy_pass http://laravel;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WebSockets realtime
    location /socket.io/ {
        proxy_pass http://realtime;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # Nuxt SSR
    location / {
        proxy_pass http://nuxt;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
